### ISSUE TITLE
Unexpected token < in JSON at position 0 while sign up

### ISSUE THREAD

**Issue by bineetNaidu** [jcbbb/thullo#1]
![Screenshot from 2020-12-04 11-37-23](https://user-images.githubusercontent.com/66471461/101128202-248f6800-3625-11eb-8d5c-765c0bc43e77.png)

While landing i get redirect back home page and get this :arrow_up: 

Network Request
![Screenshot from 2020-12-04 11-40-23](https://user-images.githubusercontent.com/66471461/101128376-8d76e000-3625-11eb-8957-0ad8ba24658b.png)

This Request URL: https://wonderful-hopper-fb0f99.netlify.app/undefined/auth/me 
__undefined/auth/me__

**Comment by jcbbb** [comment]
Yeah, it's just the frontend not connected to backend just yet )

**Comment by jcbbb** [comment]
I can't host my backend server on netlify

**Comment by bineetNaidu** [comment]
> I can't host my backend server on netlify

Well you can host it on heroku it free

**Comment by jcbbb** [comment]
@bineetNaidu Heroku is slow and shuts down the dyno if it stops receiving requests
